export const categories = [
  { slug: "class-9", title: "Class 9", description: "Build strong foundations with clear notes and chapter-wise practice.", icon: "✦", color: "mint", kind: "Class" },
  { slug: "class-10", title: "Class 10", description: "Revise smarter with subject notes and board exam practice.", icon: "▤", color: "blue", kind: "Class" },
  { slug: "class-11", title: "Class 11", description: "Make the transition to higher-level concepts feel manageable.", icon: "◈", color: "violet", kind: "Class" },
  { slug: "class-12", title: "Class 12", description: "Organise final-year revision and prepare for what comes next.", icon: "✎", color: "amber", kind: "Class" },
  { slug: "jee-main", title: "JEE Main", description: "Practice Physics, Chemistry and Mathematics by topic and year.", icon: "⌬", color: "blue", kind: "Entrance exam" },
  { slug: "jee-advanced", title: "JEE Advanced", description: "Go deeper with challenging concepts and focused practice.", icon: "⬡", color: "violet", kind: "Entrance exam" },
  { slug: "neet", title: "NEET", description: "Prepare Biology, Physics and Chemistry in one organised place.", icon: "✚", color: "mint", kind: "Entrance exam" },
  { slug: "ssc", title: "SSC", description: "Find study notes and previous year practice for SSC exams.", icon: "◎", color: "amber", kind: "Competitive exam" }
];

export const demoMaterials = [
  { id: "demo-neet-biology-2025", category_slug: "neet", type: "pyqs", year: 2025, subject_slug: "biology", subject_name: "Biology", chapter_slug: null, title: "NEET Biology Previous Year Questions 2025", description: "A sample listing for NEET Biology previous year questions. Add a PDF you have permission to distribute from the admin dashboard.", tags: ["NEET", "Biology", "PYQ", "2025"], seo_title: "NEET Biology PYQs 2025 PDF | Study Hub Junction", seo_description: "Browse NEET Biology previous year questions for 2025 on Study Hub Junction.", file_url: "", thumbnail_url: "", license_status: "not_verified", license_note: "Demo listing. Verify redistribution rights before publishing.", is_published: true },
  { id: "demo-neet-physics-2025", category_slug: "neet", type: "pyqs", year: 2025, subject_slug: "physics", subject_name: "Physics", chapter_slug: null, title: "NEET Physics Previous Year Questions 2025", description: "A sample listing for NEET Physics question practice. This demo listing does not include a PDF.", tags: ["NEET", "Physics", "PYQ", "2025"], seo_title: "NEET Physics PYQs 2025 | Study Hub Junction", seo_description: "Browse NEET Physics previous year questions for 2025.", file_url: "", thumbnail_url: "", license_status: "not_verified", license_note: "Demo listing. Verify redistribution rights before publishing.", is_published: true },
  { id: "demo-neet-chem-2025", category_slug: "neet", type: "pyqs", year: 2025, subject_slug: "chemistry", subject_name: "Chemistry", chapter_slug: null, title: "NEET Chemistry Previous Year Questions 2025", description: "A sample listing for NEET Chemistry question practice. Add your authorised file when ready.", tags: ["NEET", "Chemistry", "PYQ", "2025"], seo_title: "NEET Chemistry PYQs 2025 | Study Hub Junction", seo_description: "Browse NEET Chemistry previous year questions for 2025.", file_url: "", thumbnail_url: "", license_status: "not_verified", license_note: "Demo listing. Verify redistribution rights before publishing.", is_published: true },
  { id: "demo-jee-main-physics-2025", category_slug: "jee-main", type: "pyqs", year: 2025, subject_slug: "physics", subject_name: "Physics", chapter_slug: null, title: "JEE Main Physics Previous Year Questions 2025", description: "A sample JEE Main Physics PYQ page. Add a permitted PDF URL in the admin dashboard.", tags: ["JEE Main", "Physics", "PYQ", "2025"], seo_title: "JEE Main Physics PYQs 2025 | Study Hub Junction", seo_description: "Practice JEE Main Physics previous year questions from 2025.", file_url: "", thumbnail_url: "", license_status: "not_verified", license_note: "Demo listing. Verify redistribution rights before publishing.", is_published: true },
  { id: "demo-jee-main-chem-2025", category_slug: "jee-main", type: "pyqs", year: 2025, subject_slug: "chemistry", subject_name: "Chemistry", chapter_slug: null, title: "JEE Main Chemistry Previous Year Questions 2025", description: "A sample JEE Main Chemistry PYQ listing for the site preview.", tags: ["JEE Main", "Chemistry", "PYQ", "2025"], seo_title: "JEE Main Chemistry PYQs 2025 | Study Hub Junction", seo_description: "Practice JEE Main Chemistry previous year questions from 2025.", file_url: "", thumbnail_url: "", license_status: "not_verified", license_note: "Demo listing. Verify redistribution rights before publishing.", is_published: true },
  { id: "demo-jee-main-maths-2025", category_slug: "jee-main", type: "pyqs", year: 2025, subject_slug: "mathematics", subject_name: "Mathematics", chapter_slug: null, title: "JEE Main Mathematics Previous Year Questions 2025", description: "A sample JEE Main Mathematics PYQ listing. Real downloads are added by the site owner.", tags: ["JEE Main", "Mathematics", "PYQ", "2025"], seo_title: "JEE Main Mathematics PYQs 2025 | Study Hub Junction", seo_description: "Practice JEE Main Mathematics previous year questions from 2025.", file_url: "", thumbnail_url: "", license_status: "not_verified", license_note: "Demo listing. Verify redistribution rights before publishing.", is_published: true },
  { id: "demo-jee-physics-notes", category_slug: "jee-main", type: "notes", year: null, subject_slug: "physics", subject_name: "Physics", chapter_slug: null, title: "JEE Main Physics Notes", description: "An example notes page at the predictable URL /jee-main/notes/physics.", tags: ["JEE Main", "Physics", "Notes"], seo_title: "JEE Main Physics Notes | Study Hub Junction", seo_description: "Find JEE Main Physics notes on Study Hub Junction.", file_url: "", thumbnail_url: "", license_status: "not_verified", license_note: "Demo listing. Verify redistribution rights before publishing.", is_published: true },
  { id: "demo-class10-maths-chapter1", category_slug: "class-10", type: "chapter", year: null, subject_slug: "maths", subject_name: "Maths", chapter_slug: "chapter-1", title: "Class 10 Maths Chapter 1", description: "A sample chapter-wise listing with its direct URL /class-10/maths/chapter-1.", tags: ["Class 10", "Maths", "Chapter 1"], seo_title: "Class 10 Maths Chapter 1 | Study Hub Junction", seo_description: "Find Class 10 Maths Chapter 1 study resources.", file_url: "", thumbnail_url: "", license_status: "not_verified", license_note: "Demo listing. Verify redistribution rights before publishing.", is_published: true },
  { id: "demo-class12-chem-notes", category_slug: "class-12", type: "notes", year: null, subject_slug: "chemistry", subject_name: "Chemistry", chapter_slug: null, title: "Class 12 Chemistry Important Notes", description: "A sample Class 12 Chemistry notes listing for the site preview.", tags: ["Class 12", "Chemistry", "Notes"], seo_title: "Class 12 Chemistry Notes | Study Hub Junction", seo_description: "Explore Class 12 Chemistry notes and revision resources.", file_url: "", thumbnail_url: "", license_status: "not_verified", license_note: "Demo listing. Verify redistribution rights before publishing.", is_published: true },
  { id: "demo-ssc-pyq-2025", category_slug: "ssc", type: "pyqs", year: 2025, subject_slug: "general-awareness", subject_name: "General Awareness", chapter_slug: null, title: "SSC Previous Year Questions 2025", description: "A sample SSC previous year questions listing. Add only material that is cleared for redistribution.", tags: ["SSC", "PYQ", "2025"], seo_title: "SSC PYQs 2025 | Study Hub Junction", seo_description: "Browse SSC previous year question resources for 2025.", file_url: "", thumbnail_url: "", license_status: "not_verified", license_note: "Demo listing. Verify redistribution rights before publishing.", is_published: true }
];

export function materialPath(material) {
  const category = material.category_slug;
  const subject = material.subject_slug || "general";
  if (material.type === "chapter" && material.chapter_slug) {
    return `/${category}/${subject}/${material.chapter_slug}`;
  }
  if (material.type === "pyqs") {
    return `/${category}/pyqs/${material.year || "all-years"}${subject ? `/${subject}` : ""}`;
  }
  return `/${category}/${material.type || "notes"}/${subject}`;
}

export function makeSlug(value) {
  return value.trim().toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
